"use client"
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link"
import { ShoppingCart, Menu, X, Flame, ShoppingBag, Leaf, Facebook, Twitter, Instagram, Linkedin } from "lucide-react";
import { useState } from "react"



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {

//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => setIsMenuOpen(!isMenuOpen);
  return (

    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-amber-50 to-amber-100`}
      >
        <header className="bg-amber-200 shadow-sm">
          <div className="container mx-auto px-4 py-4 flex justify-between items-center">
            <Link href="/"><h1 className="text-2xl font-bold text-gray-800">Essenz.in</h1></Link>
            <nav className="hidden md:flex space-x-4 mr-20">
              <Link href="/" className="text-black hover:opacity-80">Home</Link>
              <Link href="/products" className="text-black hover:opacity-80">Products</Link>
              <Link href="/about" className="text-black hover:opacity-80">About</Link>
              <Link href="/contact" className="text-black hover:opacity-80">Contact</Link>

            </nav>
            <div className="flex items-center">
              <Link href='/cart'><button className="text-gray-600 hover:text-gray-800 mr-4">
                <ShoppingCart className="h-6 w-6" />
              </button></Link>
              <button className="md:hidden text-gray-600 hover:text-gray-800" onClick={toggleMenu}>
                {isMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
              </button>
            </div>
          </div>
          {/* Mobile menu */}
          {isMenuOpen && (
            <div className="md:hidden bg-amber-200 py-2">
              <Link href="/" className="block px-4 py-2 text-black">Home</Link>
              <Link href="/products" className="block px-4 py-2 text-black">Shop</Link>
              <Link href="/about" className="block px-4 py-2 text-black">About</Link>
              <Link href="/contact" className="block px-4 py-2 text-black ">Contact</Link>
            </div>
          )}
        </header>
        {children}
        {/* 
        <footer className="bg-amber-200 p-4 text-center text-amber-800">
        <p>&copy; 2024 Essenz.in All rights reserved.</p>
      </footer> */}

        <footer className="bg-amber-200 pt-4">
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap justify-between">
              <div className="w-full md:w-1/3 mb-6 md:mb-0">
                <Link href="/"> <h3 className="text-xl text-black font-semibold mb-4">Essenz.in</h3></Link>
                <p className="text-black">Illuminating spaces, one candle at a time.</p>
              </div>
              <div className="w-full md:w-1/3 mb-6 md:mb-0">
                <h4 className="text-lg font-semibold mb-4 text-black">Quick Links</h4>
                <ul className="space-y-2">
                <li><Link href="/gift-set" className="text-black hover:text-slate-700">Gift-Set</Link></li>
                  <li><Link href="/candle-care" className="text-black hover:text-slate-700">Candle Care</Link></li>
                  <li><Link href="/sustainability" className="text-black hover:text-slate-700">Sustainability</Link></li>
                  <li><Link href="/wholesale" className="text-black hover:text-slate-700">Wholesale</Link></li>
                
                </ul>
              </div>

              <div className="w-full md:w-1/3">
                <h4 className="text-lg font-semibold mb-4 text-black">Follow Us</h4>
                <div className="flex space-x-4">
                  <Link href="#"><Facebook className="text-black hover:text-slate-700" /></Link>
                  <Link href="#"><Twitter className="text-black hover:text-slate-700" /></Link>
                  <Link href="https://www.instagram.com/essenz.in/" target="_blank"><Instagram className="text-black hover:text-slate-700" /></Link>
                  <Link href="https://www.linkedin.com/company/essenzin/" target="_blank"> <Linkedin className="text-black hover:text-slate-700" /></Link>
                </div>
              </div>
            </div>
            <div className="mt-8 text-center text-black">
              <p>&copy; 2024 Essez.in All rights reserved.</p>
              <p className="mt-2">Designed By Sami</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
